### ISSUE TITLE
Delete feature is not working

### ISSUE THREAD

**Issue by Sibin987** [Sibin987/rospl-proj#1]

**Comment by Sibin987** [comment]
if request.method == 'DELETE':
        db['users'].delete_many({'_id': ObjectId(id)})
        print('\n # Deletion successful # \n')
        return jsonify({'status': 'Data id: ' + id + ' is deleted!'})

**Comment by Hardik-web** [comment]
if request.method == 'DELETE':
        db['users'].delete_many({'_id': ObjectId(id)})
        print('\n # Deletion successful # \n')
        return jsonify({'status': 'Data id: ' + id + ' is deleted!'})
